#logging.level.org.springframework: debug

server.port: 5555

spring.security.user:
  name: apiuser
  password: Pa55W0r015x!#@

spring.datasource:
  url: jdbc:postgresql://localhost:5432/todo
  username: todo
  password: password

# Quartz properties
spring.quartz:
  job-store-type: jdbc
  properties.org.quartz:
      jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate